#!/bin/sh

RED="\033[0;31m"
YELLOW="\033[1;33m"
GREEN="\033[0;32m"
NC="\033[0m"

echo -e "${RED}Running tests before commiting${NC}"

# Move into test folder and compile tests if they are different
COMP_BOOL=$( git diff tests )
if [ ! -z "${COMP_BOOL}" ]; then
    echo -e "${GREEN}Compiling tests${NC}"
    ( cd tests; make -j )
fi

# Show the tests to be passed
echo -e "${YELLOW}" "$( cd tests; ./exec_tests -l)" ${NC}
echo -e "Running tests"
# Run the tests
EXIT_CODE=$( cd tests; ./exec_tests )

# Check if error is generated 
if [[ ${EXIT_CODE} == *"All tests passed"* ]]; then
    echo -e "${GREEN}Tests passed${NC}"
else
    echo -e "${YELLOW}${EXIT_CODE}${NC}"
    echo -e "${RED}ERROR: Check your code, it does not pass tests${NC}"
    exit 1
fi
